/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:b6413d51-17bc-496f-b90a-abbf30c8a16d",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_RyCwUGo2y",
    "aws_user_pools_web_client_id": "4v2kl2q5ucvof4o5uicr0jsji0",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://tx4vqaretffyfia2btnsxy5rka.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6uqylj63wbddtmbfdjg46o3qim"
};


export default awsmobile;
